### ISSUE TITLE
On-Prem support

### ISSUE THREAD

**Issue by Heydad-Helfer** [alcideio/skan#10]
HTML output requires a connection to the internet, so it shows a blank page while running on-prem.
Is there an option to direct the external assets' requests to an internal path somehow?

**Comment by gadinaor** [comment]
@Heydad-Helfer thanks bringing this to our attention - sKan use our npmjs library to render the HTML result viewer.
... do you mirror npmjs libs to an on-prem repo? if you can share some insight how do handle this with other tools - we might be able to to address that.

**Comment by Heydad-Helfer** [comment]
Yes, we use Artifactory to mirror external repos to our network. We do have a npmjs repo clone, so we might have your module already (it's easy to import, even if not).
However, the html file generated from the scanner references to these resources with full path, so our proxy servers can't find them.
As far as I'm aware, other tools we use have a server instance on-prem that works internally, and all of the assets are pointing to this server, so it's a non-issue.

I hope it helps..
