### ISSUE TITLE
TypeError: "t.Resource.Namespace is undefined"

### ISSUE THREAD

**Issue by Mazon** [alcideio/skan#7]
**Describe the bug**
I get `TypeError: "t.Resource.Namespace is undefined"`  in  0.1.1/dist/main.js:35
and a blank view in brower when running

`helm template mychart pathtochart | skan manifest -f -`

Can see that it have findings, soo seems to understand the chart.

**Comment by gadinaor** [comment]
@Mazon thanks - a fix is underway

**Comment by Mazon** [comment]
Works, Thank you!

**Comment by gadinaor** [comment]
@Mazon gr8 ... if you like sKan ... you should definitely try this: https://www.alcide.io/pricing/free-forever/ ... it has lots of additional configuration checks.
